services:
  postgres:
    image: postgres:18.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080